version: '3'
services:
  app:
    build: .docker
    restart: always
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sql_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

networks:
  app_network:
